@startuml classes
top to bottom direction
scale 800 width
class Matricula{
    data: Date
    cancelada: bool
    semestre: string
}
abstract class Pessoa{
    nome: string
    cpf: string
    email: string
    senha: string
    telefone: string
}
class Endereco {
    logradouro: string
    numero: string
    bairro: string
    cep: string
    cidade: string
    uf: string
}
class RegistroAcesso{
    dataHora: timestamp
    ip: string
}
class Aluno {
    registroAcademico: string
}
class Professor {
    curriculo: string
}
class Administrador{
    perfilAcesso: TipoPerfilAcesso
}
enum TipoPerfilAcesso {
    basico
    assistente
    direcao
}
class Atividade{
    descricao: string
    notaMaxima: float
    tipo: TipoAtividade
}
class RetornoAtividade{
    dataHora: datetime
    textoResposta: string
    linkDocumentoResposta: string
    avaliado: bool
    dataHoraAvaliacao: datetime
    nota: decimal
}
enum TipoAtividade {
    prova
    trabalho
}
class Contrato{
    nome: string
    texto: string
    ativo: boolean
}
class Doenca{
    nome: string
}
class Doente{
    inicioQuarentena: date
    fimQuarentena: date
}
class Curso {
    nome: string
    valor: decimal
}
class ControlePresenca{
    aulaData: date
}
class Disciplina{
    nome: string
    descricao: string
    cargaHoraria: decimal
}
abstract class MaterialApoioDisciplina{
    nome: string
    dataEnvio: date
}
class MaterialApoioDisciplinaLink{
    link: string
}
class MaterialApoioDisciplinaArquivo{
    chaveCDN: string
}
class MaterialApoioDisciplinaMarkdown{
    texto: string
}
class Turma {
    dataInicio: date
    dataTermino: date
    horarios: int
    semestre: string
}
class Sala{
    Nome: string
    Localizacao: string
    Capacidade: int
}
class Documento{
    tipoDocumento: TipoDocumento
    linkArquivo: string
}
class Parcela {
    valor: decimal
    dataVencimento: date
}
class Pagamento{
    dataRealizado: date
    tipo: TipoPagamento
}
class Voucher {
    dataCadastro: date
    valor: decimal
    codigo: string
    dataValidade: date
}
class VoucherExclusivo {
    cpf: string
}
class Renegociacao{
    novoPrimeiroVencimento: date
    multa: decimal
    juros: decimal
}
class TransferenciaAluno{
    data: date
    aprovada: date
    dataLimite: date
}
class Divida{
    valorTotal: decimal
    quantidadeParcelas: int
}
class OrientacaoTCC{
    semestre: string
}
class Encontro {
    data: date
    sala: string
    linkPlataforma: string
}
class Protocolo {
    tipo: TipoProtocolo
    data: date
    encerrado: bool
}
enum TipoProtocolo{
    reclamacao
    reingresso
    cancelamento
    trancamento
    transferenciaAluno
    irpf
}
class Notificacao{
    dataEnvio: date
    texto: string
    tipo: TipoNotificacao
}
class DocumentoProfessor{
    nome: string
}
enum TipoNotificacao{
    sms
    email
    push
}
enum TipoPagamento{
    boleto
    pix
    cartaoCredito
    cartaoDebito
    cheque
}
enum TipoDocumento{
    cnh
    cpf
    diploma
    compranteResidencia
}

Pessoa <|-d- Administrador
Pessoa <|- Aluno
Pessoa <|-- Professor

MaterialApoioDisciplina <|-- MaterialApoioDisciplinaLink
MaterialApoioDisciplina <|-- MaterialApoioDisciplinaArquivo
MaterialApoioDisciplina <|-- MaterialApoioDisciplinaMarkdown

Pessoa "1" <-u- "*0..*" Endereco
Divida "1" <-- "0..*" Renegociacao
Divida "0..*" -u-> "1" Matricula
Matricula "1" <-u- "0..*" TransferenciaAluno
Matricula "1" <-u- "0..*" OrientacaoTCC
Aluno "1" <-- "0..*" Matricula
Disciplina -- Disciplina : pre-requisito
Disciplina "1" <-- "0..*" MaterialApoioDisciplina
MaterialApoioDisciplina "0..*" --> "1" Professor : autor
Matricula "0..*" --> "1" Curso
Matricula "1" *-- "1..*" Documento
Matricula "1" o-- "1" Voucher
Matricula "1" *-- "1..*" Parcela
Curso "1" -- "1..*" Disciplina
Curso "1" <-u-> "1..*" Contrato
Matricula "0..*" --> "1" Contrato : versao\ndo contrato
Pessoa "1" <-- "0..*" Protocolo
Turma "0..*" o-- "1" Sala : acontece
Turma "0..*" --o "1" Professor
Turma "1..*" <--> "1..*" Disciplina
Turma "1" <-r- "0..*" Atividade
Atividade "1" <-r- "0..*" RetornoAtividade
RetornoAtividade "0..*" --> "1" Matricula
Turma "1" *-- "0..*" ControlePresenca: estaPresente
RegistroAcesso "0..*" *-- "1" Pessoa
Doente "0..*" o-- "1" Doenca
Pessoa "1" *-- "1" Doente
Pessoa "1..*" <-- "0..*" Notificacao
Professor "1" *-- "0..*" DocumentoProfessor
Professor "1" -- "0..*" OrientacaoTCC : orienta
OrientacaoTCC "1" *-u- "1..*" Encontro
Pagamento "0..*" --> "1" Parcela
Voucher "1" <-- "0..*" VoucherExclusivo
TransferenciaAluno "0..*" o-- "1..*" Disciplina : aproveitamento\ncréditos
TransferenciaAluno "0..*" o-- "1..*" Disciplina : \nsubstituição\nde disciplina

Pagamento -- TipoPagamento
Notificacao -- TipoNotificacao
Documento -- TipoDocumento
Protocolo -- TipoProtocolo
Atividade -- TipoAtividade
Administrador -- TipoPerfilAcesso

' -u- -> up
' -d- -> down
' -l- -> left
' -r- -> right

@enduml
