@startwbs EAP

* 1. Processo de Matrícula
** 1.1. Gerenciamento\nde Login
*** 1.1.1. Autenticar por e-mail ou CPF
*** 1.1.2. Recuperar Senha
*** 1.1.3. Gerenciar Usuários
*** 1.1.4. Gerenciar Perfis de Acesso
** 1.2. Gestão de Ensino
*** 1.2.1. Gerenciar Cursos
*** 1.2.2. Gerenciar Turmas
*** 1.2.3. Gerenciar Professor
*** 1.2.4. Gerenciar Disciplinas
** 1.3. Gestão do Aluno
*** 1.3.1. Gerenciar Aluno
*** 1.3.2. Gerenciar Documentação\ndo Aluno
*** 1.3.3. Gerenciar Situação\nFinanceira do Aluno
** 1.4. Gestão de Matrícula
*** 1.4.1. Matrícula em\nCurso de Extensão
*** 1.4.2. Matrícula em\nCurso de Pós-Graduação
*** 1.4.3. Notificação de\nConfirmação de Matrícula
*** 1.4.4. Aplicar Desconto ao Curso
*** 1.4.5. Calcular Valores da\nMatrícula e de Parcelas
*** 1.4.6. Gerar Contrato com\nAceite do Aluno
** 1.5. Gestão Financeira
*** 1.5.1. Fazer Pagamento via Boleto
*** 1.5.2. Fazer Pagamento via\nCartão de Crédito
*** 1.5.3. Gerenciar Boletos dos Alunos
*** 1.5.4. Gerar Voucher Promocional
*** 1.5.5. Gerenciar Alunos Inadimplentes
*** 1.5.6. Gerar Relatório de\nAlunos Inadimplentes
** 1.6. Integrações
*** 1.6.1. Integrar com Plataforma\nde Cartão de Crédito
*** 1.6.2. Integrar com Gerador\nde Boletos

@endwbs