@startwbs EAP

* EAP
** 1. Gerenciamento do Projeto
*** 1.1. Plano do Projeto
*** 1.2. Monitoramento e Controle
*** 1.3. Lições Aprendidas
*** 1.4. Equipe
** 2. Infraestrutura
*** 2.1. Criação da arquit.
*** 2.2. Criação do repo.
*** 2.3. Config. da integ.
*** 2.4. Configuração amb.
** 3. Processo de Matrícula
*** 3.1. Visão do Aluno
****< 3.1.1. Login
**** 3.1.2. Realizar pagamento de parcelas
*** 3.2. Gestão de Ensino
****< 3.2.1. Cadastro de Cursos
****< 3.2.2. Cadastro de Turmas
**** 3.2.3. Cadastro de Professores
**** 3.2.4. Cadastro de Usuários
*** 3.3. Gestão do Aluno
**** 3.3.1. Cadastro do Aluno
****< 3.3.2. Gerenciar Documentação\ndo Aluno
*** 3.4. Gestão de Matrícula
****< 3.4.1. Processo de matrícula
**** 3.4.2. Envio dos documentos obrigatórios
**** 3.4.3. Confirmação da matrícula
*** 3.5. Gestão Financeira
****< 3.5.1. Gestão de Boletos
**** 3.5.2. Gerar Voucher Promocional
**** 3.5.3. Gestão de Alunos Inadimplentes

@endwbs