@startuml
'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
!include C4_Component.puml

LAYOUT_LEFT_RIGHT()
'LAYOUT_WITH_LEGEND()

title Diagrama Componente - Instituição ABC

Container(spa, "SPA WEB", "Angular e TypeScript", "Provê todas as funcionalidades para o Aluno ao realizar matricula utilizando browser web.")

System_Ext(boletoCloud, "API BoletoCloud", "Api de geração de boletos")
ContainerDb(dbFin, "Database ", "Banco de dados relacional SQLite", "Armazena informações financeiras, parcelas, boletos")

Container(keycloak, "KeyCloak", "Gerenciamento de identidade e acesso", "Armazena informação de registro de usuários, logs de acesso e etc.")

Container_Boundary(api, "API Application") {
    Component(cmatricula, "Controller Matricula", "MVC Rest Controller", "Provê todas as API para gestão de matriculas")
    Component(matricula, "Service Matricula", "service", "Provê as regras de negócio para gestão de matrículas")
    Component(financeiroService, "Financeiro Service", "service", "Gerencia pagamentos e mensalidades.")

    Component(cparcela, "Controller Parcela", "MVC Rest Controller", "Provê todas as API para gestão de parcelas")
    Component(parcela, "Service Parcela", "service", "Provê as regras de negócio para gestão de parcelas")

    Component(ccontrato, "Controller Contrato", "MVC Rest Controller", "Provê todas as API para gestão de contratos")
    Component(contrato, "Service Contrato", "service", "Provê as regras de negócio para gestão de contratos")

    Rel(cmatricula, matricula, "Uses")
    Rel(matricula, financeiroService, "Uses")

    Rel(cparcela, parcela, "Uses")

    Rel(parcela, financeiroService, "Uses")
}

Rel(spa, keycloak, "Uses", "JSON/HTTPS")

Rel(spa, cmatricula, "Uses", "JSON/HTTPS")
Rel(cmatricula, keycloak, "Uses", "JSON/HTTPS")

Rel(spa, cparcela, "Uses", "JSON/HTTPS")
Rel(cparcela, keycloak, "Uses", "JSON/HTTPS")

Rel(spa, ccontrato, "Uses", "JSON/HTTPS")
Rel(ccontrato, keycloak, "Uses", "JSON/HTTPS")
Rel(ccontrato, contrato, "Uses", "JSON/HTTPS")

Rel(financeiroService, dbFin, "Uses")
Rel(contrato, dbFin, "Uses")

Rel(financeiroService, boletoCloud, "Uses")
@enduml


'Nivel 3 da matricula os passos
'componente de confirmar pagto
'coponente de confirmar documentos
'compoenente de confirmar turma disponibilidade
'compoenente de agendar cobranças futuras