@startuml classes
top to bottom direction
scale 800 width
title Grupo 7: Airton Felipe Sauer de Oliveira, Andressa Friedrichs, Felipe Amadeu Junges e Marcelo Aloísio da Silva

class Curso{
    descricao: string
}
class Turma{
    numero: string
}
class Prova {
    peso: decimal
    dataHoraInicio: datetime
    dateHoraTermino: datetime
}
abstract class Questao {
    percentualPeso: decimal
    enunciado:string
}
class QuestaoMultiplaEscolha {
}
class QuestaoRelacionamento {
}
class RespostaMultiplaEscolha{
    letra: string
    texto: string
    correta: bool
}
class RespostaRelacionamento {
    colunaA: string
    colunaB: string
}

' --

abstract class RespostaAluno {
    pontuacao: decimal
}
class RespostaAlunoMultiplaEscolha {
  correta: bool
  letraSelecionada: string
}
class RespostaAlunoRelacionar {
    colunaA: string
    colunaB: string
}
class Aluno {
  nome: string
}
class ProvaAluno {
    dataHoraInicio: datetime
    dateHoraEntrega: datetime
    notaFinal: decimal
}

Questao <|-u- QuestaoMultiplaEscolha
Questao <|-u- QuestaoRelacionamento
RespostaAluno <|-u- RespostaAlunoMultiplaEscolha
RespostaAluno <|-u- RespostaAlunoRelacionar

Turma "1..*" --> "1" Curso
Prova "0..*" --> "1" Turma
Questao "1..*" --* "1" Prova
RespostaMultiplaEscolha "5" <-- "1" QuestaoMultiplaEscolha
RespostaRelacionamento "2..5" <-- "1" QuestaoRelacionamento
Aluno "1" <-u- "1..*" ProvaAluno
ProvaAluno "1..*" -left---> "1" Prova : pertence
RespostaAluno "1..*" <-- "1" ProvaAluno
RespostaAluno "0..*" -left-> "1" Questao
Aluno "0..*" -left- "1..*" Turma : matriculado

'  - horizontal
' -- vertical

@enduml
