@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

'LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

title Diagrama Container - Instituição ABC

Person(aluno, "Aluno da Instituição","Um aluno com matricula ativa")
Person(admin, "Administrativo da Instituição", "Funcionario administrativo")
Person(direcao, "Direção da Instituição", "Funcionario da Direção")

Enterprise_Boundary(c1, "API Gateway") {

        Container(systemFinanceiro, "Sistema Financeiro", "desc sistema professor")
        Container(systemAdministrativo, "Sistema Administrativo", "desc sistema professor")

        Container(systemDirecao, "Sistema Direção", "desc sistema direção")
        Container(systemMatricula, "Sistema Matricula", "desc sistema Matricula")
}

'Rel_U, Rel_Up
'Rel_D, Rel_Down
'Rel_L, Rel_Left
'Rel_R, Rel_Right

Rel(aluno, systemMatricula , "Realiza Matricula\nGerencia Documentação", "Requisição HTTPS/JSON")
Rel(aluno, systemFinanceiro , "Gerencia pagamentos", "Requisição HTTPS/JSON")

Rel(admin, systemAdministrativo , "Gerencia Documentação", "Requisição HTTPS/JSON")
Rel(admin, systemFinanceiro , "Gerencia pagamentos\nGerencia Financeiro", "Requisição HTTPS/JSON")
Rel(admin, systemMatricula , "Gerencia pagamentos\nGerencia Documentação\nGerencia Financeiro", "Requisição HTTPS/JSON")
Rel(direcao, systemDirecao , "Gerencia Professores\nGerenciar Cursos", "Requisição HTTPS/JSON")
Rel(direcao, systemFinanceiro , "Gerencia Financeiro", "Requisição HTTPS/JSON")

@enduml